"use client"
import { useContext, useRef } from "react"
import { AppContext } from "../context/appContext"
import { Download, Trophy, Zap, Target, Type, Calendar } from "lucide-react"
import html2canvas from "html2canvas"

const ResultCard = () => {
  const { wpm, cpm, accuracy, duration, testMode, codeLanguage, theme } = useContext(AppContext)
  const cardRef = useRef<HTMLDivElement>(null)

  const downloadCard = async () => {
    if (cardRef.current) {
      try {
        const canvas = await html2canvas(cardRef.current, {
          backgroundColor: theme === "dark" ? "#1f2937" : "#ffffff",
          scale: 2,
        })

        const link = document.createElement("a")
        link.download = `typing-test-result-${Date.now()}.png`
        link.href = canvas.toDataURL()
        link.click()
      } catch (error) {
        console.error("Error generating image:", error)
      }
    }
  }

  const getPerformanceLevel = () => {
    if (wpm >= 70)
      return {
        level: "Expert",
        color: "text-purple-600 dark:text-purple-400",
        bg: "bg-purple-100 dark:bg-purple-900/30",
      }
    if (wpm >= 50)
      return { level: "Advanced", color: "text-blue-600 dark:text-blue-400", bg: "bg-blue-100 dark:bg-blue-900/30" }
    if (wpm >= 30)
      return {
        level: "Intermediate",
        color: "text-green-600 dark:text-green-400",
        bg: "bg-green-100 dark:bg-green-900/30",
      }
    return {
      level: "Beginner",
      color: "text-orange-600 dark:text-orange-400",
      bg: "bg-orange-100 dark:bg-orange-900/30",
    }
  }

  const performance = getPerformanceLevel()

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50">
      <div className="bg-white dark:bg-gray-900 rounded-2xl p-8 max-w-md w-full shadow-2xl">
        <div ref={cardRef} className="bg-white dark:bg-gray-900 p-8 rounded-2xl">
          {/* Header */}
          <div className="text-center mb-8">
            <div className={`inline-flex items-center space-x-2 px-4 py-2 rounded-full ${performance.bg} mb-4`}>
              <Trophy className={`w-5 h-5 ${performance.color}`} />
              <span className={`font-semibold ${performance.color}`}>{performance.level}</span>
            </div>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">Test Complete!</h2>
            <p className="text-gray-600 dark:text-gray-400">
              {testMode === "code" ? `${codeLanguage.charAt(0).toUpperCase() + codeLanguage.slice(1)} Code` : "Words"} •{" "}
              {duration}s
            </p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-2 gap-4 mb-8">
            <div className="text-center p-4 bg-gray-50 dark:bg-gray-800 rounded-xl">
              <Zap className="w-6 h-6 text-green-500 mx-auto mb-2" />
              <p className="text-3xl font-bold text-gray-900 dark:text-white">{wpm}</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">WPM</p>
            </div>
            <div className="text-center p-4 bg-gray-50 dark:bg-gray-800 rounded-xl">
              <Target className="w-6 h-6 text-blue-500 mx-auto mb-2" />
              <p className="text-3xl font-bold text-gray-900 dark:text-white">{accuracy}%</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Accuracy</p>
            </div>
            <div className="text-center p-4 bg-gray-50 dark:bg-gray-800 rounded-xl">
              <Type className="w-6 h-6 text-purple-500 mx-auto mb-2" />
              <p className="text-3xl font-bold text-gray-900 dark:text-white">{cpm}</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">CPM</p>
            </div>
            <div className="text-center p-4 bg-gray-50 dark:bg-gray-800 rounded-xl">
              <Calendar className="w-6 h-6 text-orange-500 mx-auto mb-2" />
              <p className="text-3xl font-bold text-gray-900 dark:text-white">{duration}s</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">Duration</p>
            </div>
          </div>

          {/* Footer */}
          <div className="text-center">
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">Generated by TypeMaster</p>
            <p className="text-xs text-gray-400 dark:text-gray-500">{new Date().toLocaleDateString()}</p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex space-x-4 mt-6">
          <button
            onClick={downloadCard}
            className="flex-1 flex items-center justify-center space-x-2 bg-blue-500 hover:bg-blue-600 text-white px-4 py-3 rounded-xl font-medium transition-colors"
          >
            <Download size={20} />
            <span>Download</span>
          </button>
          <button
            onClick={() => window.location.reload()}
            className="flex-1 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 px-4 py-3 rounded-xl font-medium transition-colors"
          >
            Try Again
          </button>
        </div>
      </div>
    </div>
  )
}

export default ResultCard
