import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./context/appContext";

const inter = Inter({ subsets: ["latin"] });
const merriweather = Merriweather({ weight: ["300", "400", "700", "900"], subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
